version: '3'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: textmagic_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - db
        networks:
            - textmagic-network
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: textmagic_php82
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/project
#        command: sh -c "composer install && npm install && npm run build && while true; do sleep 30; done;"
        depends_on:
            - db
        networks:
            - textmagic-network
    db:
        image: postgres:15-alpine
        container_name: textmagic_postgres15
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgresql:/var/lib/postgresql/data:rw
        restart: on-failure
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        networks:
            - textmagic-network
networks:
    textmagic-network:
